# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Antony's Portfolio
tagline:          Black Theme for Jekyll
description:      "A CPA with many varied experiences wanting to apply his technical and observational skills to the field of audit work"
url:              https://github.com/indrejue
baseurl:          https://indrejue.github.io/
                  # the optional subpath of your site, e.g. "/my-jekyll-site/"
                  # This will apply to all pages in your Jekyll site.

author:
  name:           Antony Farag
  url:            

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/my-jekyll-site/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            2.0.1

github:
  repo:             https://github.com/Indrejue
